 @MyDemoApi_HostAddress = http://localhost:7077

GET http://localhost:7077/api/Product
Accept: application/json
 
###
POST {{MyDemoApi_HostAddress}}/api/Product
Accept: application/json
Content-Type: application/json

{
  "Name": "Product 1",
  "Price": 100
}